name: Build

on: 
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore NuGet packages
        run: dotnet restore C#inDepthBook.sln
        
      - name: Build
        run: dotnet build --no-restore C#inDepthBook.sln